# railway.toml

[docs]
  name = "TON Connect App"

[build]
  builder = "Nixpacks"

[start]
  cmd = "node server.js"
  forward_ports = true

[deploy]
  num_instances = 1
  healthcheck_path = "/"
